#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dogtail
Version  : 0.9.9
Release  : 3
URL      : http://pypi.debian.net/dogtail/dogtail-0.9.9.tar.gz
Source0  : http://pypi.debian.net/dogtail/dogtail-0.9.9.tar.gz
Summary  : GUI test tool and automation framework that uses Accessibility (a11y) technologies to communicate with desktop applications.
Group    : Development/Tools
License  : GPL-2.0
Requires: dogtail-bin
Requires: dogtail-python3
Requires: dogtail-data
Requires: dogtail-doc
Requires: dogtail-python
BuildRequires : pbr
BuildRequires : pip

BuildRequires : python3-dev
BuildRequires : setuptools

%description
GUI test tool and automation framework that uses assistive technologies to 
communicate with desktop applications.

%package bin
Summary: bin components for the dogtail package.
Group: Binaries
Requires: dogtail-data

%description bin
bin components for the dogtail package.


%package data
Summary: data components for the dogtail package.
Group: Data

%description data
data components for the dogtail package.


%package doc
Summary: doc components for the dogtail package.
Group: Documentation

%description doc
doc components for the dogtail package.


%package python
Summary: python components for the dogtail package.
Group: Default
Requires: dogtail-python3

%description python
python components for the dogtail package.


%package python3
Summary: python3 components for the dogtail package.
Group: Default
Requires: python3-core

%description python3
python3 components for the dogtail package.


%prep
%setup -q -n dogtail-0.9.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1518715999
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dogtail-detect-session
/usr/bin/dogtail-logout
/usr/bin/dogtail-run-headless
/usr/bin/dogtail-run-headless-next
/usr/bin/sniff

%files data
%defattr(-,root,root,-)
/usr/share/applications/sniff.desktop
/usr/share/dogtail/glade/sniff.ui
/usr/share/dogtail/icons/button.xpm
/usr/share/dogtail/icons/checkbutton.xpm
/usr/share/dogtail/icons/checkmenuitem.xpm
/usr/share/dogtail/icons/colorselection.xpm
/usr/share/dogtail/icons/combo.xpm
/usr/share/dogtail/icons/dialog.xpm
/usr/share/dogtail/icons/image.xpm
/usr/share/dogtail/icons/label.xpm
/usr/share/dogtail/icons/menubar.xpm
/usr/share/dogtail/icons/menuitem.xpm
/usr/share/dogtail/icons/notebook.xpm
/usr/share/dogtail/icons/scrolledwindow.xpm
/usr/share/dogtail/icons/spinbutton.xpm
/usr/share/dogtail/icons/statusbar.xpm
/usr/share/dogtail/icons/table.xpm
/usr/share/dogtail/icons/text.xpm
/usr/share/dogtail/icons/toolbar.xpm
/usr/share/dogtail/icons/tree.xpm
/usr/share/dogtail/icons/treeitem.xpm
/usr/share/dogtail/icons/unknown.xpm
/usr/share/dogtail/icons/viewport.xpm
/usr/share/dogtail/icons/vscrollbar.xpm
/usr/share/dogtail/icons/vseparator.xpm
/usr/share/dogtail/icons/window.xpm
/usr/share/icons/hicolor/scalable/apps/dogtail-head.svg
/usr/share/icons/hicolor/scalable/apps/dogtail-tail.svg

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/dogtail/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
